import { Metadata } from "next"

export const metadata : Metadata = {
  title: {
    default: "Next.js tutorial - KingPine",
    template: "%s | KingPine"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "darkcyan",
            padding: "1rem",
            color: "white"
          }}>
          <p>header</p>
        </header>{children}
        <footer
          style={{
            backgroundColor: "coral",
            padding: "1rem",
            color: "white"
          }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
